#!/usr/bin/bash
sudo ufw status verbose
sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw allow ssh
sudo ufw allow 22
sudo ufw allow http
sudo ufw allow 80
sudo ufw allow https
sudo ufw allow 443


sudo ufw enable

sudo ufw status verbose
